apiVersion: v1
kind: Service
metadata:
  name: pythonapp
  namespace: flask
spec:
  type: LoadBalancer
  selector:
    app: pythonapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080